version: 0.0
os: linux
files:             
#defining hooks in appspec 
hooks:
  BeforeInstall:
    - location: ./beforeInstall.sh
      timeout: 180
      runas: centos
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 180
      runas: centos
