version: 2
 jobs:
  build:
    working_directory: ~/webapp
    filters:
      branches:
        only:
          - master

    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout 
      - run:
          name: Build WAR
          command: | 
            cd webapp
            ./mvnw clean install
            cd target
            ls -al
            cd ../../..
      - run :
          name : Install pip
          command: |
                   sudo apt update
                   sudo apt-get install python3
                   python3 --version
                   sudo apt install python3-pip
                   pip3 --version
      - run :
          name  : Zip Artifact
          command : |
                    echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
                    pwd
                    ls -al
                    mkdir -p codedeploy_artifact
                    cp infrastructure/aws/codedeploy/*.sh .
                    zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/target/WEBAPP.war *.sh *.yml
                    ls -al
                    mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
                    ls -al
                    pwd
                    cd codedeploy_artifact
                    ls -al
                    pwd
                    cd ..
                    pwd
                    ls -al
      - run :
          name  :   AWS CLI Install 
          command :  sudo pip3 install awscli
      - run :
          name : Upload Artifact To S3
          command : | 
                 
                  echo "Uploading to S3 bucket"
                  cd codedeploy_artifact
                  aws s3 cp csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${bucketName}
                  
                 
                 
      -run :
          name : Make CodeDeploy API call 
          command : |
                echo "CodeDeploy"
                aws deploy create-deployment --application-name ${applicationName} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${groupName} --s3-location bucket=${bucketName},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip

           
