version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11-jdk-stretch
    steps:
    - checkout
    - run:
        name: Build WAR
        command: |
          pwd
          cd webapp/
          pwd
          ls -al
          ./mvnw clean install
          cd target
          ls -al
          cd ../..
    - run :
        name  : Zip Artifact
        command : |
          echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
          pwd
          find . -name appspec.yml
          ls -al
          mkdir -p codedeploy_artifact
          find ./infrastructure/aws/codedeploy/ -name *.sh
          cp infrastructure/aws/codedeploy/*.sh .
          find . -name *.yml
          zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp/target/ROOT.war *.sh *.yml
          ls -al
          mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
          ls -al
          pwd
          cd codedeploy_artifact
          ls -al
          pwd
          cd ..
          pwd
          ls -al
    - run :
        name : Install pip
        command: |
          sudo apt install python3-pip
          pip3 --version
    - run :
        name  :   AWS CLI Install
        command :  sudo pip3 install awscli
    - run :
        name : Upload Artifact To S3
        command : |
          echo "Uploading to S3 bucket"
          cd codedeploy_artifact
          aws s3 cp csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://${AWS_CODE_DEPLOY_BUCKET}
    - run :
        name : Make CodeDeploy API call
        command : |
          aws deploy create-deployment \
          --application-name csye6225-webapp \
          --region ${AWS_REGION} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name csye6225-webapp-deployment \
          --s3-location bucket=code-deploy.${AWS_CODE_DEPLOY_BUCKET}.me,bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip