version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout 
      - run:
          name: Build WAR
          command: |
            pwd
            cd webapp/
            pwd
            ls -al
            ./mvnw clean install
            cd target
            ls -al
            cd ../..
      - run :
          name  : Zip Artifact
          command : |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            find . -name appspec.yml
            ls -al
            mkdir -p codedeploy_artifact
            find ./infrastructure/aws/codedeploy/ -name *.sh
            cp infrastructure/aws/codedeploy/*.sh .
            find . -name *.yml
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp/target/ROOT.war *.sh *.yml
            ls -al
            mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run :
          name : Install pip
          command: |
            sudo rm /etc/apt/sources.list
            sudo apt-get clean
            sudo apt-get update
            echo "Success"
            sudo apt-get install python
            python --version
            apt-get update
            sudo apt-get install python-pip
            pip --version
      - run :
          name  :   AWS CLI Install 
          command :  sudo pip3 install -y awscli
      - run :
          name : Upload Artifact To S3
          command : |            
            echo "Uploading to S3 bucket"
            cd codedeploy_artifact
            aws s3 cp csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://${AWS_CODE_DEPLOY_BUCKET}
      - run :
          name : Make CodeDeploy API call 
          command : |
            echo "CodeDeploy"
            # aws deploy create-deployment --application-name ${applicationName} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${groupName} --s3-location bucket=${bucketName},bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
            aws deploy register-application-revision --application-name csye6225-webapp \
            --revision revisionType=S3,s3Location={bucket=${AWS_CODE_DEPLOY_BUCKET},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip,bundleType=zip} \
            --s3-location bucket=${AWS_CODE_DEPLOY_BUCKET},bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
            echo "------------------------------------------------------"
            aws deploy list-application-revision --application-name csye6225-webapp \
            --s3-bucket ${AWS_CODE_DEPLOY_BUCKET} --deployed include
            echo "------------------------------------------------------"
            deploymentId=$(aws deploy create-deployment \
            --application-name csye6225-webapp \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name csye6225-webapp-deployment \
            --s3-location bucket=${AWS_CODE_DEPLOY_BUCKET},bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip \
            --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE,DEPLOYMENT_STOP_ON_ALARM,DEPLOYMENT_STOP_ON_REQUEST)
            echo "$deploymentId"
              
